sonar.projectKey=olakitanakinya_NetflixClone   # Use the actual key from URL
sonar.organization=olakitanakinya
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.typescript.lcov.reportPaths=coverage/lcov.info
