# SonarCloud project key – must match the project key in SonarCloud URL
sonar.projectKey=olakitanakinya_NetflixClone
# Your SonarCloud organization name
sonar.organization=olakitanakinya

# Source directories
sonar.sources=.
# Exclude node_modules and test files from analysis
sonar.exclusions=**/node_modules/**,**/*.test.js

# Test directories and reports
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.typescript.lcov.reportPaths=coverage/lcov.info