sonar.projectKey=NetflixClone
sonar.organization=olakitanakinya
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.typescript.lcov.reportPaths=coverage/lcov.info
