name: Build, Analyze, Scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build
    runs-on: build-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step: Install unzip (required for SonarScanner)
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      # Step: SonarCloud Scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # No SONAR_HOST_URL needed – action will use SonarCloud by default
        # Optionally, you can specify the project properties file location:
        # with:
        #   projectBaseDir: .
        #   args: >
        #     -Dsonar.projectKey=olakitanakinya_NetflixClone
        #     -Dsonar.organization=olakitanakinya-github

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
          trivy fs .

      - name: Docker build and push
        run: |
          docker build --build-arg TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }} -t netflix .
          docker tag netflix ${{ secrets.DOCKERHUB_USERNAME }}/netflix:latest
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/netflix:latest

  deploy:
    needs: build-analyze-scan
    runs-on: deploy-runner
    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Pull the docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/netflix:latest

      - name: Trivy image scan
        run: trivy image ${{ secrets.DOCKERHUB_USERNAME }}/netflix:latest

      - name: Run the container netflix
        run: |
          docker rm -f netflix || true
          docker run -d --name netflix -p 8081:80 ${{ secrets.DOCKERHUB_USERNAME }}/netflix:latest